on: [push, pull_request]
name: ci
jobs:
  build:
    name: "Sham on '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["current"]
        racket-variant: ["regular", "CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.3
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: |
             sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
             sudo apt-get install libllvm10 llvm-10 llvm-10-dev llvm-10-runtime
             raco pkg install --auto -t dir sham-astg sham-llvm sham-test
      - run: raco test -x -p sham-test
